# Generated by Django 5.1.1 on 2024-09-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0002_project_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='example description -- this can be up to 250 characters', max_length=250),
            preserve_default=False,
        ),
    ]
