# Generated by Django 5.1.1 on 2024-09-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='instructions',
            field=models.CharField(default='test', max_length=4000),
            preserve_default=False,
        ),
    ]
